package com.vordain.guard.child

object ChildVpnSmokeLabels {
    const val TITLE = "Vordain Guard"
    const val BUILD_LABEL = "Debug smoke test"
    const val SUBTITLE = "VPN shell smoke test"
    const val VPN_PERMISSION_PREFIX = "VPN permission"
    const val LAST_COMMAND_PREFIX = "Last command"
    const val SHELL_STATUS_PREFIX = "Shell status"
    const val PERMISSION_UNKNOWN = "Unknown"
    const val PERMISSION_REQUIRED = "Permission required"
    const val PERMISSION_GRANTED = "Permission granted / prepared"
    const val COMMAND_NONE = "None"
    const val COMMAND_PERMISSION_REQUESTED = "Permission requested"
    const val COMMAND_START_SENT = "Start shell sent"
    const val COMMAND_STOP_SENT = "Stop shell sent"
    const val COMMAND_LAB_START_SENT = "Start lab capture sent"
    const val COMMAND_LAB_STOP_SENT = "Stop lab capture sent"
    const val STATUS_NOT_RUNNING = "Not running"
    const val STATUS_PERMISSION_REQUIRED = "Permission required"
    const val STATUS_PERMISSION_GRANTED = "Permission granted - tap Start VPN shell"
    const val STATUS_STARTING_SHELL = "Starting shell"
    const val STATUS_SHELL_COMMAND_SENT = "Shell command sent"
    const val STATUS_SHELL_ACTIVE = "VPN shell active - filtering not enabled yet"
    const val STATUS_LAB_CAPTURE_STARTING = "Starting lab capture"
    const val STATUS_LAB_CAPTURE_ACTIVE = "Lab capture command sent - packets are dropped locally"
    const val STATUS_STOP_COMMAND_SENT = "Stop command sent"
    const val STATUS_STOPPED = "Stopped"
    const val STATUS_REVOKED_UNKNOWN = "Revoked/unknown"
    const val REQUEST_PERMISSION_BUTTON = "Request VPN permission"
    const val START_BUTTON = "Start VPN shell"
    const val STOP_BUTTON = "Stop VPN shell"
    const val COPY_DIAGNOSTICS_BUTTON = "Copy diagnostics"
    const val WARNING = "This build does not filter traffic yet."
    const val LAB_WARNING = "This mode routes tablet traffic into Vordain and drops it. Internet may stop until you press Stop."
    const val LAB_LOCAL_ONLY = "Local test only. No traffic leaves the device from this capture. No forwarding yet."
    const val LAB_DNS_LOCAL_ONLY = "DNS observations are local and in-memory only."
    const val LAB_DNS_SINKHOLE = "Blocked DNS queries receive a local synthetic response."
    const val LAB_ALLOWED_DROPPED = "Allowed traffic is still not forwarded."
    const val LAB_INTERNET_MAY_NOT_WORK = "Internet may still not work in lab mode."
    const val LAB_NOT_FULL_PROTECTION = "Not full protection - no forwarding yet."
    const val DIAGNOSTICS_COPIED = "Diagnostics copied"
}
