package com.vordain.guard.child

object ChildVpnSmokeLabels {
    const val TITLE = "Vordain Guard"
    const val BUILD_LABEL = "Debug smoke test"
    const val SUBTITLE = "VPN shell smoke test"
    const val VPN_PERMISSION_PREFIX = "VPN permission"
    const val LAST_COMMAND_PREFIX = "Last command"
    const val SHELL_STATUS_PREFIX = "Shell status"
    const val PERMISSION_UNKNOWN = "Unknown"
    const val PERMISSION_REQUIRED = "Permission required"
    const val PERMISSION_GRANTED = "Permission granted / prepared"
    const val COMMAND_NONE = "None"
    const val COMMAND_PERMISSION_REQUESTED = "Permission requested"
    const val COMMAND_START_SENT = "Start shell sent"
    const val COMMAND_STOP_SENT = "Stop shell sent"
    const val STATUS_NOT_RUNNING = "Not running"
    const val STATUS_PERMISSION_REQUIRED = "Permission required"
    const val STATUS_PERMISSION_GRANTED = "Permission granted - tap Start VPN shell"
    const val STATUS_STARTING_SHELL = "Starting shell"
    const val STATUS_SHELL_COMMAND_SENT = "Shell command sent"
    const val STATUS_SHELL_ACTIVE = "VPN shell active - filtering not enabled yet"
    const val STATUS_STOP_COMMAND_SENT = "Stop command sent"
    const val STATUS_STOPPED = "Stopped"
    const val STATUS_REVOKED_UNKNOWN = "Revoked/unknown"
    const val REQUEST_PERMISSION_BUTTON = "Request VPN permission"
    const val START_BUTTON = "Start VPN shell"
    const val STOP_BUTTON = "Stop VPN shell"
    const val COPY_DIAGNOSTICS_BUTTON = "Copy diagnostics"
    const val WARNING = "This build does not filter traffic yet."
    const val DIAGNOSTICS_COPIED = "Diagnostics copied"
}
